apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-app
  template: 
    metadata: 
      labels: 
        app: nginx-app
    spec:
      containers:
      - name:   nginx-app
        image: nginx:alpine
        imagePullPolicy: Always
        ports: 
        - containerPort: 80

---

apiVersion: v1 
kind: Service 
metadata:
  name: nginx-app-svc
spec:
  selector: 
    app: nginx-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
  